# Generated by Django 6.0.2 on 2026-03-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0011_organization_is_deleted"),
        ("sourcecode", "0002_alter_debugsymbolbundle_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, default="")),
                ("provider", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("hidden", "Hidden"),
                            ("pending_deletion", "Pending Deletion"),
                            ("deletion_in_progress", "Deletion In Progress"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=["organization", "name"],
                name="sourcecode_repository_unique_org_name",
            ),
        ),
    ]
