-- TransactionGroup V3: Hash-partitioned by organization_id
-- Replaces the unpartitioned TransactionGroup table with a hash-partitioned version.
-- Hash partitions use settings.PARTITION_HASH_BUCKETS (created by RunPython step).

-- 1. Drop old unpartitioned table (if it exists).
DROP TABLE IF EXISTS performance_transactiongroup CASCADE;

-- 2. Create new hash-partitioned table.
CREATE TABLE performance_transactiongroup (
    -- 8-byte alignment: auto PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- 8-byte alignment: FKs
    organization_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,

    -- Variable-width fields
    transaction VARCHAR(1024) NOT NULL,
    op VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL DEFAULT '',

    -- 8-byte alignment: timestamps
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    first_seen TIMESTAMPTZ NOT NULL,
    last_seen TIMESTAMPTZ NOT NULL,

    -- 8-byte alignment: floats
    avg_duration DOUBLE PRECISION NOT NULL DEFAULT 0,
    p50 DOUBLE PRECISION,
    p95 DOUBLE PRECISION,

    -- 8-byte alignment: big integers
    count BIGINT NOT NULL DEFAULT 0 CHECK ("count" >= 0),
    error_count BIGINT NOT NULL DEFAULT 0 CHECK ("error_count" >= 0),

    -- Variable-width
    duration_histogram JSONB NOT NULL DEFAULT '{}',

    PRIMARY KEY (id, organization_id)
) PARTITION BY HASH (organization_id);

-- 3. Add constraints and indexes.
ALTER TABLE performance_transactiongroup
    ADD CONSTRAINT unique_transaction_project_op_method
    UNIQUE (transaction, project_id, op, method, organization_id);

CREATE INDEX perf_txgroup_org_lastseen
    ON performance_transactiongroup (organization_id, last_seen);

CREATE INDEX performance_transactiongroup_created
    ON performance_transactiongroup (created);

-- No DB-level FK constraints: partitioned tables cannot be the target of a
-- foreign key, and DB-level FKs on the partitioned side cause "cannot truncate
-- a table referenced in a foreign key constraint" during Django's test flush.
-- ORM FK fields (DO_NOTHING) still provide joins and validation.
