-- TransactionGroup V3: Hash-partitioned by organization_id
-- Replaces the unpartitioned TransactionGroup table with a hash-partitioned version.
-- Hash partitions use settings.PARTITION_HASH_BUCKETS (created by RunPython step).

-- 1. Create new partitioned table
CREATE TABLE performance_transactiongroup_new (
    -- 8-byte alignment: auto PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- 8-byte alignment: FKs
    organization_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,

    -- Variable-width fields
    transaction VARCHAR(1024) NOT NULL,
    op VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL DEFAULT '',

    -- 8-byte alignment: timestamps
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    first_seen TIMESTAMPTZ NOT NULL,
    last_seen TIMESTAMPTZ NOT NULL,

    -- 8-byte alignment: floats
    avg_duration DOUBLE PRECISION NOT NULL DEFAULT 0,
    p50 DOUBLE PRECISION,
    p95 DOUBLE PRECISION,

    -- 8-byte alignment: big integers
    count BIGINT NOT NULL DEFAULT 0,
    error_count BIGINT NOT NULL DEFAULT 0,

    -- Variable-width
    duration_histogram JSONB NOT NULL DEFAULT '{}',

    PRIMARY KEY (id, organization_id)
) PARTITION BY HASH (organization_id);

-- 2. Backfill from old table (if it exists) and swap.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'performance_transactiongroup'
    ) THEN
        -- Old table has no first_seen/last_seen; use created as both.
        INSERT INTO performance_transactiongroup_new
            (id, organization_id, project_id, transaction, op, method, created,
             first_seen, last_seen)
        SELECT
            tg.id,
            p.organization_id,
            tg.project_id,
            tg.transaction,
            tg.op,
            tg.method,
            tg.created,
            tg.created,
            tg.created
        FROM performance_transactiongroup tg
        JOIN projects_project p ON tg.project_id = p.id;

        -- Reset identity sequence to continue after max existing id
        PERFORM setval(
            pg_get_serial_sequence('performance_transactiongroup_new', 'id'),
            GREATEST(
                (SELECT COALESCE(MAX(id), 0) FROM performance_transactiongroup_new),
                1
            )
        );

        DROP TABLE performance_transactiongroup CASCADE;
    END IF;
END $$;

-- 3. Rename new table to final name
ALTER TABLE performance_transactiongroup_new
    RENAME TO performance_transactiongroup;

-- 4. Rename PK index and identity sequence to match table name
ALTER INDEX IF EXISTS performance_transactiongroup_new_pkey
    RENAME TO performance_transactiongroup_pkey;

DO $$
DECLARE
    seq_name TEXT;
BEGIN
    SELECT pg_get_serial_sequence('performance_transactiongroup', 'id') INTO seq_name;
    IF seq_name IS NOT NULL AND seq_name LIKE '%_new_%' THEN
        EXECUTE format('ALTER SEQUENCE %s RENAME TO performance_transactiongroup_id_seq', seq_name);
    END IF;
END $$;

-- 5. Add constraints and indexes
ALTER TABLE performance_transactiongroup
    ADD CONSTRAINT unique_transaction_project_op_method
    UNIQUE (transaction, project_id, op, method, organization_id);

CREATE INDEX perf_txgroup_org_lastseen
    ON performance_transactiongroup (organization_id, last_seen);

CREATE INDEX performance_transactiongroup_created
    ON performance_transactiongroup (created);

-- FKs (DEFERRABLE for bulk operations)
ALTER TABLE performance_transactiongroup
    ADD CONSTRAINT perf_txgroup_organization_fk
    FOREIGN KEY (organization_id) REFERENCES organizations_ext_organization(id)
    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE performance_transactiongroup
    ADD CONSTRAINT perf_txgroup_project_fk
    FOREIGN KEY (project_id) REFERENCES projects_project(id)
    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
