# Generated by Django 6.0.2 on 2026-02-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alertrecipient_tags_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrecipient',
            name='recipient_type',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'General Slack-compatible webhook'), ('discord', 'Discord'), ('googlechat', 'Google Chat webhook'), ('ntfy', 'ntfy')], max_length=16),
        ),
    ]
