# Generated by Django 6.0.2 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0012_add_ntfy_recipient_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrecipient",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "General Slack-compatible webhook"),
                    ("discord", "Discord"),
                    ("googlechat", "Google Chat webhook"),
                    ("ntfy", "ntfy"),
                    ("teams", "Microsoft Teams"),
                ],
                max_length=16,
            ),
        ),
    ]
