# Generated by Django 6.0.4 on 2026-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add independent uptime failure threshold fields (quantity / timespan
    minutes) to ProjectAlert so uptime alerts can fire only after N failed
    checks within M minutes."""

    dependencies = [
        ("alerts", "0015_add_feishu_recipient_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectalert",
            name="uptime_quantity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectalert",
            name="uptime_timespan_minutes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
