# Generated by Django 6.0.1 on 2026-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_auto_20251117_2129"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="downsample_rate",
            field=models.FloatField(
                default=0.1,
                help_text="Fraction of events to keep in sample (0.0 to 1.0) when downsampling old data.",
            ),
        ),
    ]
