# Generated by Django 6.0.1 on 2026-01-28 19:48

from pathlib import Path

from django.db import migrations


def load_sql(filename):
    sql_path = Path(__file__).parent / "sql" / filename
    return sql_path.read_text()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0010_alter_organization_id"),
        ("projects", "0019_storage_v2_project_stats"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql("create_log_stats.sql"),
            reverse_sql="DROP TABLE IF EXISTS projects_logprojecthourlystatistic CASCADE;",
        ),
    ]
