# Generated by Django 6.0.2 on 2026-02-08 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_storage_v2_project_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="downsample_rate",
            field=models.FloatField(
                default=0.1,
                help_text="Fraction of non-representative events to keep full data during downsampling (0.0=no downsampling)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
