# Generated by Django 6.0.2 on 2026-02-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0010_alter_organization_id"),
        ("projects", "0020_add_log_statistics_and_quota"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE projects_logprojecthourlystatistic ADD COLUMN environment VARCHAR(255) NOT NULL DEFAULT '';
                    ALTER TABLE projects_logprojecthourlystatistic DROP CONSTRAINT projects_logprojecthourlystatistic_pkey;
                    ALTER TABLE projects_logprojecthourlystatistic ADD PRIMARY KEY (project_id, organization_id, date, level, service_bucket, environment);
                    """,
                    reverse_sql="""
                    ALTER TABLE projects_logprojecthourlystatistic DROP CONSTRAINT projects_logprojecthourlystatistic_pkey;
                    ALTER TABLE projects_logprojecthourlystatistic ADD PRIMARY KEY (project_id, organization_id, date, level, service_bucket);
                    ALTER TABLE projects_logprojecthourlystatistic DROP COLUMN environment;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="LogProjectHourlyStatistic",
                    fields=[
                        ("date", models.DateTimeField()),
                        ("count", models.PositiveIntegerField()),
                        ("level", models.PositiveSmallIntegerField()),
                        (
                            "service_bucket",
                            models.PositiveSmallIntegerField(
                                default=0,
                                help_text="Hash bucket for service name (0-255)",
                            ),
                        ),
                        (
                            "environment",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Deployment environment",
                                max_length=255,
                            ),
                        ),
                        (
                            "pk",
                            models.CompositePrimaryKey(
                                "project",
                                "organization",
                                "date",
                                "level",
                                "service_bucket",
                                "environment",
                                blank=True,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "organization",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="organizations_ext.organization",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="projects.project",
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                ),
            ],
        ),
    ]
