# Generated by Django 6.0 on 2026-01-05 02:30
# Manually optimized

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import glitchtip.model_utils
import psql_partition.backend.migrations.operations.create_partitioned_model
import psql_partition.manager.manager
import psql_partition.models.partitioned
import psql_partition.types
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.shared.migration_utils import get_sql_content


# --- Define SQL for the Advanced Path (from 0004) ---
CREATE_ADVANCED_PARTITION_SQL = """
    CREATE TABLE "issue_events_issueaggregate" (
        "issue_id" BIGINT NOT NULL,
        "organization_id" INTEGER NOT NULL,
        "date" TIMESTAMPTZ NOT NULL,
        "count" INTEGER NOT NULL,
        PRIMARY KEY ("issue_id", "organization_id", "date")
    ) PARTITION BY HASH (organization_id);

    CREATE TABLE issue_events_issueaggregate_p0 PARTITION OF issue_events_issueaggregate FOR VALUES WITH (MODULUS 4, REMAINDER 0) PARTITION BY RANGE (date);
    CREATE TABLE issue_events_issueaggregate_p1 PARTITION OF issue_events_issueaggregate FOR VALUES WITH (MODULUS 4, REMAINDER 1) PARTITION BY RANGE (date);
    CREATE TABLE issue_events_issueaggregate_p2 PARTITION OF issue_events_issueaggregate FOR VALUES WITH (MODULUS 4, REMAINDER 2) PARTITION BY RANGE (date);
    CREATE TABLE issue_events_issueaggregate_p3 PARTITION OF issue_events_issueaggregate FOR VALUES WITH (MODULUS 4, REMAINDER 3) PARTITION BY RANGE (date);
"""
DROP_TABLE_SQL = 'DROP TABLE IF EXISTS "issue_events_issueaggregate";'


class Migration(migrations.Migration):
    replaces = [
        ("issue_events", "0001_initial"),
        ("issue_events", "0002_issueevent_hashes_and_more"),
        ("issue_events", "0003_auto_20250527_2204"),
        ("issue_events", "0004_auto_20250626_1630"),
        ("issue_events", "0005_issue_issue_title_trgm_idx"),
        ("issue_events", "0006_replace_tsvector_function"),
    ]

    initial = True

    dependencies = [
        ("organizations_ext", "0010_alter_organization_id"),
        ("projects", "0014_auto_20240318_1449"),
        ("projects", "0017_auto_20250627_1413"),
        (
            "releases",
            "0001_squashed_0004_alter_release_id_alter_releasefile_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = (
        [
            # Create Comment model
            migrations.CreateModel(
                name="Comment",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("created", models.DateTimeField(auto_now_add=True)),
                    ("text", models.TextField(blank=True, null=True)),
                    (
                        "user",
                        models.ForeignKey(
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name="+",
                            to=settings.AUTH_USER_MODEL,
                        ),
                    ),
                ],
                options={
                    "ordering": ("-created",),
                },
            ),
            # Create Issue model (columns ordered for optimal data alignment)
            migrations.CreateModel(
                name="Issue",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "project",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="issues",
                            to="projects.project",
                        ),
                    ),
                    (
                        "first_seen",
                        models.DateTimeField(
                            db_index=True, default=django.utils.timezone.now
                        ),
                    ),
                    (
                        "last_seen",
                        models.DateTimeField(
                            db_index=True, default=django.utils.timezone.now
                        ),
                    ),
                    ("count", models.PositiveIntegerField(default=1, editable=False)),
                    ("short_id", models.PositiveIntegerField(null=True)),
                    (
                        "level",
                        models.PositiveSmallIntegerField(
                            choices=[
                                (0, "sample"),
                                (1, "debug"),
                                (2, "info"),
                                (3, "warning"),
                                (4, "error"),
                                (5, "fatal"),
                            ],
                            default=4,
                        ),
                    ),
                    (
                        "type",
                        models.PositiveSmallIntegerField(
                            choices=[(0, "default"), (1, "error"), (2, "csp")],
                            default=0,
                        ),
                    ),
                    (
                        "status",
                        models.PositiveSmallIntegerField(
                            choices=[
                                (0, "unresolved"),
                                (1, "resolved"),
                                (2, "ignored"),
                            ],
                            default=0,
                        ),
                    ),
                    ("is_deleted", models.BooleanField(default=False)),
                    ("is_public", models.BooleanField(default=False)),
                    (
                        "culprit",
                        models.CharField(blank=True, max_length=1024, null=True),
                    ),
                    ("title", models.CharField(max_length=255)),
                    ("metadata", models.JSONField()),
                    (
                        "search_vector",
                        django.contrib.postgres.search.SearchVectorField(
                            default="", editable=False
                        ),
                    ),
                ],
                options={
                    "base_manager_name": "objects",
                },
            ),
            # Create IssueEvent model with hashes field included (optimized from 0001 + 0002)
            # Columns ordered for optimal data alignment: 16-byte, 8-byte, 2-byte, then variable-width
            psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
                name="IssueEvent",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    (
                        "timestamp",
                        models.DateTimeField(help_text="Time at which event happened"),
                    ),
                    (
                        "received",
                        models.DateTimeField(
                            help_text="Time at which GlitchTip accepted event"
                        ),
                    ),
                    (
                        "issue",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="issue_events.issue",
                        ),
                    ),
                    (
                        "release",
                        models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to="releases.release",
                        ),
                    ),
                    (
                        "type",
                        models.PositiveSmallIntegerField(
                            choices=[(0, "default"), (1, "error"), (2, "csp")],
                            default=0,
                        ),
                    ),
                    (
                        "level",
                        models.PositiveSmallIntegerField(
                            choices=[
                                (0, "sample"),
                                (1, "debug"),
                                (2, "info"),
                                (3, "warning"),
                                (4, "error"),
                                (5, "fatal"),
                            ],
                            default=4,
                        ),
                    ),
                    ("title", models.CharField(max_length=255)),
                    ("transaction", models.CharField(max_length=200)),
                    ("data", models.JSONField()),
                    ("tags", models.JSONField()),
                    (
                        "hashes",
                        django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=32), db_default=[]
                        ),
                    ),
                ],
                partitioning_options={
                    "method": psql_partition.types.PostgresPartitioningMethod["RANGE"],
                    "key": ["received"],
                },
                bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
                managers=[
                    ("objects", psql_partition.manager.manager.PostgresManager()),
                ],
            ),
            # Add indexes for IssueEvent
            migrations.AddIndex(
                model_name="issueevent",
                index=models.Index(
                    fields=["issue", "-received"], name="issue_event_issue_i_3b4e7f_idx"
                ),
            ),
            migrations.AddIndex(
                model_name="issueevent",
                index=django.contrib.postgres.indexes.GinIndex(
                    fields=["hashes"], name="issue_event_hashes_eedb7c_gin"
                ),
            ),
            # Create default partition for IssueEvent
            glitchtip.model_utils.TestDefaultPartition(
                model_name="IssueEvent",
                name="default",
            ),
            # Create IssueHash model
            migrations.CreateModel(
                name="IssueHash",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("value", models.UUIDField(db_index=True)),
                    (
                        "issue",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="hashes",
                            to="issue_events.issue",
                        ),
                    ),
                    (
                        "project",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="+",
                            to="projects.project",
                        ),
                    ),
                ],
            ),
            # Create IssueTag model (columns ordered for optimal data alignment)
            psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
                name="IssueTag",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "issue",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="issue_events.issue",
                        ),
                    ),
                    ("date", models.DateTimeField()),
                    ("count", models.PositiveIntegerField(default=1)),
                ],
                partitioning_options={
                    "method": psql_partition.types.PostgresPartitioningMethod["RANGE"],
                    "key": ["date"],
                },
                bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
                managers=[
                    ("objects", psql_partition.manager.manager.PostgresManager()),
                ],
            ),
            # Create default partition for IssueTag
            glitchtip.model_utils.TestDefaultPartition(
                model_name="IssueTag",
                name="default",
            ),
            # Create TagKey model
            migrations.CreateModel(
                name="TagKey",
                fields=[
                    ("id", models.AutoField(primary_key=True, serialize=False)),
                    ("key", models.CharField(max_length=255, unique=True)),
                ],
            ),
            # Create TagValue model
            migrations.CreateModel(
                name="TagValue",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("value", models.CharField(max_length=255, unique=True)),
                ],
            ),
            # Add foreign keys to Comment
            migrations.AddField(
                model_name="comment",
                name="issue",
                field=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="comments",
                    to="issue_events.issue",
                ),
            ),
            # Add foreign keys to IssueTag
            migrations.AddField(
                model_name="issuetag",
                name="tag_key",
                field=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to="issue_events.tagkey",
                ),
            ),
            migrations.AddField(
                model_name="issuetag",
                name="tag_value",
                field=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to="issue_events.tagvalue",
                ),
            ),
            # Create UserReport model (columns ordered for optimal data alignment)
            migrations.CreateModel(
                name="UserReport",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "issue",
                        models.ForeignKey(
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            to="issue_events.issue",
                        ),
                    ),
                    (
                        "project",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="+",
                            to="projects.project",
                        ),
                    ),
                    ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                    ("event_id", models.UUIDField()),
                    ("name", models.CharField(max_length=128)),
                    ("email", models.EmailField(max_length=254)),
                    ("comments", models.TextField()),
                ],
            ),
            # Add indexes and constraints for Issue
            migrations.AddIndex(
                model_name="issue",
                index=django.contrib.postgres.indexes.GinIndex(
                    fields=["search_vector"], name="issue_event_search__346c17_gin"
                ),
            ),
            migrations.AddConstraint(
                model_name="issue",
                constraint=models.UniqueConstraint(
                    fields=("project", "short_id"), name="project_short_id_unique"
                ),
            ),
            # Add constraint for IssueHash
            migrations.AddConstraint(
                model_name="issuehash",
                constraint=models.UniqueConstraint(
                    fields=("project", "value"), name="issue hash project"
                ),
            ),
            # Add constraint for IssueTag
            migrations.AddConstraint(
                model_name="issuetag",
                constraint=models.UniqueConstraint(
                    fields=("issue", "date", "tag_key", "tag_value"),
                    name="issue_tag_key_value_unique",
                ),
            ),
            # Add constraint for UserReport
            migrations.AddConstraint(
                model_name="userreport",
                constraint=models.UniqueConstraint(
                    fields=("project", "event_id"), name="project_event_unique"
                ),
            ),
            # From migration 0004: Create IssueAggregate with advanced partitioning support
            migrations.SeparateDatabaseAndState(
                state_operations=[
                    psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
                        name="IssueAggregate",
                        fields=[
                            (
                                "issue",
                                models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to="issue_events.issue",
                                ),
                            ),
                            (
                                "organization",
                                models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to="organizations_ext.organization",
                                ),
                            ),
                            ("date", models.DateTimeField()),
                            ("count", models.PositiveIntegerField()),
                            (
                                "pk",
                                models.CompositePrimaryKey(
                                    "issue",
                                    "organization",
                                    "date",
                                    blank=True,
                                    editable=False,
                                    primary_key=True,
                                    serialize=False,
                                ),
                            ),
                        ],
                        options={
                            "abstract": False,
                        },
                        partitioning_options={
                            "method": psql_partition.types.PostgresPartitioningMethod[
                                "RANGE"
                            ],
                            "key": ["date"],
                        },
                        bases=(
                            psql_partition.models.partitioned.PostgresPartitionedModel,
                        ),
                        managers=[
                            (
                                "objects",
                                psql_partition.manager.manager.PostgresManager(),
                            ),
                        ],
                    ),
                    glitchtip.model_utils.TestDefaultPartition(
                        model_name="IssueAggregate",
                        name="default",
                    ),
                ],
                database_operations=[
                    migrations.RunSQL(
                        CREATE_ADVANCED_PARTITION_SQL
                        if settings.GLITCHTIP_ADVANCED_PARTITIONING
                        else migrations.RunSQL.noop,
                        reverse_sql=DROP_TABLE_SQL,
                    ),
                ]
                if settings.GLITCHTIP_ADVANCED_PARTITIONING
                else [],
            )
            if settings.GLITCHTIP_ADVANCED_PARTITIONING
            else migrations.RunPython(
                migrations.RunPython.noop, migrations.RunPython.noop
            ),
            # Conditional state-only operations for non-advanced partitioning
        ]
        + (
            []
            if settings.GLITCHTIP_ADVANCED_PARTITIONING
            else [
                psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
                    name="IssueAggregate",
                    fields=[
                        (
                            "issue",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="issue_events.issue",
                            ),
                        ),
                        (
                            "organization",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="organizations_ext.organization",
                            ),
                        ),
                        ("date", models.DateTimeField()),
                        ("count", models.PositiveIntegerField()),
                        (
                            "pk",
                            models.CompositePrimaryKey(
                                "issue",
                                "organization",
                                "date",
                                blank=True,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                    partitioning_options={
                        "method": psql_partition.types.PostgresPartitioningMethod[
                            "RANGE"
                        ],
                        "key": ["date"],
                    },
                    bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
                    managers=[
                        ("objects", psql_partition.manager.manager.PostgresManager()),
                    ],
                ),
                glitchtip.model_utils.TestDefaultPartition(
                    model_name="IssueAggregate",
                    name="default",
                ),
            ]
        )
        + [
            # From migration 0005: Enable trigram extension and add title index
            django.contrib.postgres.operations.TrigramExtension(),
            migrations.AddIndex(
                model_name="issue",
                index=django.contrib.postgres.indexes.GinIndex(
                    fields=["title"],
                    name="issue_title_trgm_idx",
                    opclasses=["gin_trgm_ops"],
                ),
            ),
            # From migration 0006: Create tsvector function
            migrations.RunSQL(
                sql=get_sql_content(__file__, "append_and_limit_tsvector.sql"),
                reverse_sql="DROP FUNCTION IF EXISTS append_and_limit_tsvector(tsvector, TEXT, INTEGER, REGCONFIG);",
            ),
        ]
    )
