# Generated by Django 5.2.7 on 2025-10-15 20:42

from django.conf import settings
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


# --- SQL for the Advanced Path ---
CREATE_ADVANCED_PARTITION_SQL = """
    CREATE TABLE "issue_events_issuesearchindex" (
        "is_deleted" BOOLEAN NOT NULL DEFAULT FALSE,
        "issue_id" BIGINT NOT NULL,
        "organization_id" INTEGER NOT NULL,
        "fts_document" TSVECTOR NOT NULL DEFAULT '',
        "pattern_text" TEXT NOT NULL DEFAULT '',
        PRIMARY KEY ("organization_id", "issue_id")
    ) PARTITION BY HASH (organization_id);

    CREATE TABLE issue_events_issuesearchindex_p0 PARTITION OF issue_events_issuesearchindex FOR VALUES WITH (MODULUS 4, REMAINDER 0);
    CREATE TABLE issue_events_issuesearchindex_p1 PARTITION OF issue_events_issuesearchindex FOR VALUES WITH (MODULUS 4, REMAINDER 1);
    CREATE TABLE issue_events_issuesearchindex_p2 PARTITION OF issue_events_issuesearchindex FOR VALUES WITH (MODULUS 4, REMAINDER 2);
    CREATE TABLE issue_events_issuesearchindex_p3 PARTITION OF issue_events_issuesearchindex FOR VALUES WITH (MODULUS 4, REMAINDER 3);
"""
DROP_TABLE_SQL = 'DROP TABLE IF EXISTS "issue_events_issuesearchindex";'


# --- Operations for Django's Model State (used by both paths) ---
state_operations = [
    migrations.CreateModel(
        name="IssueSearchIndex",
        fields=[
            ("is_deleted", models.BooleanField(default=False)),
            (
                "pk",
                models.CompositePrimaryKey(
                    "issue", "organization", primary_key=True, serialize=False
                ),
            ),
            (
                "fts_document",
                django.contrib.postgres.search.SearchVectorField(
                    default="", editable=False
                ),
            ),
            (
                "pattern_text",
                models.TextField(default="", blank=True, editable=False),
            ),
            (
                "issue",
                models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="search_index_record",
                    to="issue_events.issue",
                ),
            ),
            (
                "organization",
                models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="search_index_records",
                    to="organizations_ext.organization",
                ),
            ),
        ],
        options={
            "abstract": False,
        },
    ),
]

if settings.GLITCHTIP_ADVANCED_PARTITIONING:
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[
                migrations.RunSQL(
                    CREATE_ADVANCED_PARTITION_SQL, reverse_sql=DROP_TABLE_SQL
                ),
            ],
        ),
    ]
else:
    # For standard installations, just run the regular CreateModel.
    # This will create a normal, non-partitioned table.
    operations = state_operations


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0005_issue_issue_title_trgm_idx"),
        ("organizations_ext", "0010_alter_organization_id"),
    ]

    operations = operations
