# Generated by Django 6.0.1 on 2026-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0001_squashed_0006_replace_tsvector_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueevent",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
