# Generated by Django 6.0.2 on 2026-02-10 14:29
# State-only: the FK constraints for tag_key and tag_value were never
# created in the raw SQL migration (create_issue_tag_v2.sql), so there
# is nothing to drop.  This migration updates Django's migration state
# to match the actual database.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0013_drop_tagvalue_like_index"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="issuetag",
                    name="tag_key",
                    field=models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issue_events.tagkey",
                    ),
                ),
                migrations.AlterField(
                    model_name="issuetag",
                    name="tag_value",
                    field=models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issue_events.tagvalue",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
