# Generated by Django 6.0.2 on 2026-03-04 01:48
# Manually split: column add (instant) + index creation (concurrent, non-blocking).

import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("issue_events", "0016_add_last_release_resolved_in_release"),
        ("sourcecode", "0003_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="sourcecode.repository",
                db_index=False,
            ),
        ),
        AddIndexConcurrently(
            model_name="issue",
            index=models.Index(
                fields=["repository"], name="issue_events_issue_repo_id"
            ),
        ),
    ]
