# Generated by Django 6.0.2 on 2026-03-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0016_add_last_release_resolved_in_release"),
        ("sourcecode", "0003_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="sourcecode.repository",
            ),
        ),
    ]
