# Generated by Django 6.0.4 on 2026-04-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_events', '0017_drop_issue_id_fk_on_partitioned_tables'),
        ('organizations_ext', '0011_organization_is_deleted'),
        ('teams', '0001_squashed_0005_alter_team_members_alter_team_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_to_org_user',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations_ext.organizationuser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to_team',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(condition=models.Q(('assigned_to_org_user__isnull', False)), fields=['assigned_to_org_user'], name='issue_assigned_org_user_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(condition=models.Q(('assigned_to_team__isnull', False)), fields=['assigned_to_team'], name='issue_assigned_team_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_to_org_user__isnull', True), ('assigned_to_team__isnull', True), _connector='OR'), name='issue_assigned_to_user_xor_team'),
        ),
    ]
