# Generated by Django 6.0.4 on 2026-06-30 02:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_events', '0022_drop_issue_hot_columns'),
        ('organizations_ext', '0011_organization_is_deleted'),
        ('releases', '0009_release_repository'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issueevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='issue_event_tags_53d190_gin'),
        ),
    ]
