# Generated by Django 6.0.1 on 2026-01-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0012_alter_stripesubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeprice",
            name="interval",
            field=models.CharField(default="month", max_length=20),
        ),
        migrations.AddField(
            model_name="stripeprice",
            name="no_throttle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="subscription_cycle_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="subscription_cycle_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
