# Generated by Django 6.0.3 on 2026-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0013_stripeprice_interval_stripeprice_no_throttle"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeproduct",
            name="marketing_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
