# Generated by Django 6.0.4 on 2026-04-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0014_add_marketing_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeprice",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
