# Generated by Django 6.0.4 on 2026-06-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0016_supportlicense"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeprice",
            name="is_metered",
            field=models.BooleanField(
                default=False,
                help_text="Usage-based price backed by a Stripe Billing Meter (tiered).",
            ),
        ),
        migrations.AddField(
            model_name="stripeprice",
            name="meter_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="stripeproduct",
            name="is_overage",
            field=models.BooleanField(
                default=False,
                help_text="Metered overage product (Stripe metadata product_type=overage).",
            ),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="metered_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe subscription item id for the metered overage price.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="overage_period_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Cycle anchor for overage_units_reported; counter resets when the current cycle start moves past this.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="overage_units_reported",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Cumulative billable overage events reported to the meter this cycle. Meter events are additive, so we report deltas.",
            ),
        ),
    ]
