# Generated by Django 6.0.4 on 2026-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0016_supportlicense"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportLicenseWelcome",
            fields=[
                (
                    "stripe_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
