# Generated by Django 6.0.2 on 2026-02-10 14:29
# State-only: the indexes declared by db_index=True were never created
# in the raw SQL migration (create_performance_v2.sql), so there is
# nothing to drop.  This migration updates Django's migration state to
# match the actual database.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0019_add_transactionevent_group_id_index"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="transactionevent",
                    name="duration",
                    field=models.PositiveIntegerField(help_text="Milliseconds"),
                ),
                migrations.AlterField(
                    model_name="transactionevent",
                    name="start_timestamp",
                    field=models.DateTimeField(
                        help_text="Datetime reported by client as the time the measurement started",
                    ),
                ),
                migrations.AlterField(
                    model_name="transactionevent",
                    name="trace_id",
                    field=models.UUIDField(),
                ),
            ],
            database_operations=[],
        ),
    ]
