# Generated by Django 6.0.3 on 2026-03-20 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uptime", "0014_backfill_cached_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MaxValueValidator(604800),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
