# Generated by Django 6.0.4 on 2026-06-11 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uptime", "0016_add_org_date_index_to_hourly_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MaxValueValidator(86400),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
