# Generated by Django 6.0.4 on 2026-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add cached_down_alerted to Monitor to dedup uptime down alerts: tracks
    whether a 'down' alert has already been sent for the current outage."""

    dependencies = [
        ("uptime", "0016_add_org_date_index_to_hourly_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="cached_down_alerted",
            field=models.BooleanField(default=False),
        ),
    ]
