# Generated by Django 6.0.4 on 2026-06-13 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0017_alter_monitor_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='cached_consecutive_down',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive failing checks observed so far. Drives the confirmation_threshold debounce; reset to 0 on any successful check.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='confirmation_threshold',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of consecutive failed checks before the monitor is considered down and a notification is sent. 1 alerts on the first failure.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
