# Generated by Django 6.0.2 on 2026-02-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0007_alter_release_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deploy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("environment", models.CharField(max_length=64)),
                ("url", models.CharField(blank=True, default="", max_length=200)),
                ("date_started", models.DateTimeField(blank=True, null=True)),
                ("date_finished", models.DateTimeField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deploys",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
