# Generated by Django 6.0.4 on 2026-05-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0011_organization_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="license_billing_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="license_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
