# Generated by Django 6.0.2 on 2026-02-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
        ("organizations_ext", "0010_alter_organization_id"),
        ("projects", "0020_add_log_statistics_and_quota"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE logs_logevent ADD COLUMN environment VARCHAR(255) NOT NULL DEFAULT '';
                    ALTER TABLE logs_logevent ADD COLUMN host VARCHAR(255) NOT NULL DEFAULT '';
                    CREATE INDEX logevent_org_svc_idx ON logs_logevent (organization_id, service, id DESC);
                    CREATE INDEX logevent_org_env_idx ON logs_logevent (organization_id, environment, id DESC);
                    CREATE INDEX logevent_org_host_idx ON logs_logevent (organization_id, host, id DESC);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS logevent_org_host_idx;
                    DROP INDEX IF EXISTS logevent_org_env_idx;
                    DROP INDEX IF EXISTS logevent_org_svc_idx;
                    ALTER TABLE logs_logevent DROP COLUMN host;
                    ALTER TABLE logs_logevent DROP COLUMN environment;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="logevent",
                    name="environment",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="Deployment environment (e.g. production, staging)",
                        max_length=255,
                    ),
                ),
                migrations.AddField(
                    model_name="logevent",
                    name="host",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="Host name that emitted the log",
                        max_length=255,
                    ),
                ),
                migrations.AddIndex(
                    model_name="logevent",
                    index=models.Index(
                        fields=["organization", "service", "-id"],
                        name="logevent_org_svc_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="logevent",
                    index=models.Index(
                        fields=["organization", "environment", "-id"],
                        name="logevent_org_env_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="logevent",
                    index=models.Index(
                        fields=["organization", "host", "-id"],
                        name="logevent_org_host_idx",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Resource name", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("service", "service"),
                            ("environment", "environment"),
                            ("host", "host"),
                        ],
                        default="service",
                        help_text="Type of resource (service/environment/host)",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="logservice",
            name="logservice_org_idx",
        ),
        migrations.RemoveConstraint(
            model_name="logservice",
            name="unique_org_service",
        ),
        migrations.AddIndex(
            model_name="logresource",
            index=models.Index(
                fields=["organization", "type"], name="logresource_org_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="logresource",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "type"), name="unique_org_resource"
            ),
        ),
        migrations.DeleteModel(
            name="LogService",
        ),
    ]
