# Generated by Django 6.0.1 on 2026-01-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_add_search_indexes"),
        ("organizations_ext", "0010_alter_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Service name", max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization"], name="logservice_org_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"), name="unique_org_service"
                    )
                ],
            },
        ),
    ]
