# Generated by Django 6.0.2 on 2026-02-14 23:34

import apps.api_tokens.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("client_secret", models.CharField(max_length=255)),
                ("client_id_issued_at", models.IntegerField()),
                (
                    "client_secret_expires_at",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "client_info",
                    models.JSONField(
                        help_text="Full OAuthClientInformationFull for round-trip fidelity"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OAuthRefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.api_tokens.models.generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "access_token_key",
                    models.CharField(
                        help_text="The access token string, for paired revocation",
                        max_length=64,
                    ),
                ),
                (
                    "scopes",
                    models.TextField(blank=True, help_text="Space-separated scopes"),
                ),
                ("expires_at", models.IntegerField(blank=True, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="oauth.oauthapplication",
                        to_field="client_id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
