# Generated by Django 6.0.2 on 2026-02-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthapplication',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
